name: HeadBlocks
main: com.hybris.bukkit.headblocks.HeadBlocks
version: 0.8
website: 
author: Hybris95,Socolin
description: 
             Allow authorized users to change their Head by giving the required Block
commands:
    hb:
        description: To use Headblocks functionnalities
        usage: /hb <s|self|o|other|undoself|us|undoother|uo> [playerName] [<<blockName>[:<data>]>]